### ISSUE TITLE
Exeption on Startup

### ISSUE THREAD

**Issue by TureBentzin** [RoootTheFox/RaspiBot#1]
While developing a new way to go with the ShipCommand I got this:

[main] INFO net.dv8tion.jda.api.JDA - Login Successful!
[main] INFO com.zaxxer.hikari.HikariDataSource - raspibot - Starting...
[main] INFO com.zaxxer.hikari.HikariDataSource - raspibot - Start completed.
[JDA MainWS-WriteThread] INFO net.dv8tion.jda.internal.requests.WebSocketClient - Connected to WebSocket
[JDA MainWS-ReadThread] INFO net.dv8tion.jda.api.JDA - Finished Loading!
[JDA MainWS-ReadThread] ERROR net.dv8tion.jda.api.JDA - One of the EventListeners had an uncaught exception
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:222)
	at net.ddns.rootrobo.RaspiBot.events.ReadyEvent.onReady(ReadyEvent.java:17)
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:435)
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:149)
	at net.dv8tion.jda.internal.requests.WebSocketClient.ready(WebSocketClient.java:201)
	at net.dv8tion.jda.internal.handle.GuildSetupController.checkReady(GuildSetupController.java:115)
	at net.dv8tion.jda.internal.handle.GuildSetupController.ready(GuildSetupController.java:102)
	at net.dv8tion.jda.internal.handle.GuildSetupNode.completeSetup(GuildSetupNode.java:375)
	at net.dv8tion.jda.internal.handle.GuildSetupNode.handleMemberChunk(GuildSetupNode.java:258)
	at net.dv8tion.jda.internal.handle.GuildSetupNode.ensureMembers(GuildSetupNode.java:392)
	at net.dv8tion.jda.internal.handle.GuildSetupNode.handleCreate(GuildSetupNode.java:218)
	at net.dv8tion.jda.internal.handle.GuildSetupController.onCreate(GuildSetupController.java:170)
	at net.dv8tion.jda.internal.handle.GuildCreateHandler.handleInternally(GuildCreateHandler.java:44)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:956)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:843)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:821)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:994)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

I report this here because its related to code written by @RootRobo

**Comment by lewdfoxgirl** [comment]
Is the DEVELOPER_ID String in Main.java set? If it is, do you share Servers with the bot?

**Comment by TureBentzin** [comment]
ID was not set - maybe I will add custom Exceptions to the bot in a further patch

**Comment by lewdfoxgirl** [comment]
I might move the DEVELOPER_ID to the config file as well
